channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21
  - scipy=1.7
  - pandas=1.3
  - scikit-learn=1.0
  - matplotlib
  - networkx
  - pytorch=1.10
  - cudatoolkit=10.2
  - openpyxl=3.0
  - requests
  - pip
  - tqdm
# Dev stuff
  - ipykernel
  - jupyter
  - black
  - pylint
  - flake8

